import { createApp } from "vue";
import "./style/style.css";
import App from "./App.vue";
import router from "./Router";
import UiComponents from "./ui_components";
import store from "./Store";
const app = createApp(App);
UiComponents.map((component) => app.component(component.name, component));
app.use(store);
app.use(router);
app.mount("#app");
